### ISSUE TITLE
Update Token url

### ISSUE THREAD

**Issue by shishirpy** [CareEvolution/mydatahelps-rest-api-python-quickstart#2]
Token url has changed to `https://mydatahelps.org/identityserver/connect/token`, code needs to be updated to reflect that.

**Comment by lynnfaraday** [comment]
Thank you for the contribution. The token URL https://designer.mydatahelps.org/identityserver/connect/token does work, but omitting 'designer' is admittedly simpler.

**Comment by shishirpy** [comment]
Interesting, it hadn't worked for me earlier. But it works now.

**Comment by lynnfaraday** [comment]
Sorry to hear you were having trouble, but glad it's working now.
